openapi: 3.0.0
info:
  title: API de Conversao de Moedas do Reino SRM
  description: |
    API para gerenciar conversoes entre Ouro Real e Tibar no Mercado de Pulgas dos Mil Saberes.
  version: 1.0.0
servers:
  - url: /api/v1
    description: Servidor principal

paths:
  /moedas:
    get:
      summary: Lista as moedas disponiveis (Ouro Real e Tibar)
      tags:
        - Moedas
      responses:
        '200':
          description: Lista de moedas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoedaOutput'
    post:
      summary: Criacao de Moedas
      tags:
        - Moedas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoedaInput'
      responses:
        '201':
          description: Lista de moedas retornada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoedaOutput'

  /taxas-cambio:
    get:
      summary: Obtem a taxa de cambio atual entre Ouro Real e Tibar
      tags:
        - Taxa Cambio
      responses:
        '200':
          description: Taxa de cambio atual retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxaCambioOutput'
    post:
      summary: Atualiza a taxa de cambio entre Ouro Real e Tibar
      tags:
        - Taxa Cambio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxaCambioInput'
      responses:
        '200':
          description: Taxa de cambio atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxaCambioOutput'
  /taxas-cambio/{id}:
    put:
      summary: Atualiza a taxa de cambio entre Ouro Real e Tibar
      tags:
        - Taxa Cambio
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da taxa de cambio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxaCambioUpdate'
      responses:
        '200':
          description: Taxa de cambio atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxaCambioOutput'

  /produtos:
    get:
      summary: Lista todos os produtos disponiveis para negociacao
      tags:
        - Produtos
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProdutoOutput'
    post:
      summary: Adiciona um novo produto
      tags:
        - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoInput'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoOutput'

  /transacoes:
    get:
      summary: Lista as transacoes realizadas
      tags:
        - Transacoes
      responses:
        '200':
          description: Lista de transacoes retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransacaoOutput'
    post:
      summary: Registra uma nova transacao
      tags:
        - Transacoes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoInput'
      responses:
        '201':
          description: Transacao registrada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransacaoOutput'

components:
  schemas:
    MoedaInput:
      type: object
      properties:
        nome:
          type: string
        simbolo:
          type: string
        descricao:
          type: string
      required:
        - id
        - nome
    MoedaOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        simbolo:
          type: string
        descricao:
          type: string
      required:
        - id
        - nome
        - simbolo

    TaxaCambioInput:
      type: object
      properties:
        moedaOrigemId:
          type: integer
          format: int64
        moedaDestinoId:
          type: integer
          format: int64
        taxa:
          type: number
          format: double
      required:
        - moedaOrigemId
        - moedaDestinoId
        - taxa

    TaxaCambioOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        moedaOrigem:
          $ref: '#/components/schemas/MoedaOutput'
        moedaDestino:
          $ref: '#/components/schemas/MoedaOutput'
        taxa:
          type: number
          format: double
        dataCriacao:
          type: string
          format: date-time
      required:
        - id
        - moedaOrigem
        - moedaDestino
        - taxa

    TaxaCambioUpdate:
      type: object
      properties:
        moedaOrigemId:
          type: integer
          format: int64
        moedaDestinoId:
          type: integer
          format: int64
        taxa:
          type: number
          format: double

    ProdutoOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        descricao:
          type: string
        preco:
          type: number
          format: double
        qualidade:
          type: string
          enum:
            - ruim
            - media
            - boa
            - otima
        reinoOrigem:
          $ref: '#/components/schemas/ReinoOutput'
      required:
        - id
        - nome
        - preco
        - qualidade
        - reinoOrigem

    ProdutoInput:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        preco:
          type: number
          format: double
        qualidade:
          type: string
          enum:
            - ruim
            - media
            - boa
            - otima
        reinoOrigem:
          type: string
      required:
        - id
        - nome
        - preco
        - qualidade
        - reinoOrigem

    TransacaoOutput:
      type: object
      properties:
        id:
          type: integer
          format: int64
        produto:
          $ref: '#/components/schemas/ProdutoOutput'
        moeda:
          $ref: '#/components/schemas/MoedaOutput'
        valorConvertido:
          type: number
          format: double
        quantidade:
          type: integer
        reinoOrigem:
          $ref: '#/components/schemas/ReinoOutput'
        dataTransacao:
          type: string
          format: date-time
      required:
        - id
        - produto
        - moeda
        - valorConvertido
        - quantidade
        - reinoOrigem
        - dataTransacao

    TransacaoInput:
      type: object
      properties:
        produtoId:
          type: integer
          format: int64
        quantidade:
          type: integer
        valor:
          type: number
          format: double
        moedaId:
          type: integer
          format: int64
        reinoOrigem:
          type: string
      required:
        - produtoId
        - moedaOrigemId
        - moedaDestinoId
        - valorOriginal

    ReinoOutput:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
      required:
        - nome
        - taxaUtilizada
        - quantidade
        - reinoOrigem
