version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: srm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: srm_db
    ports:
      - "5432:5432"
    volumes:
      - srm-postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: unless-stopped

volumes:
  srm-postgres-data:
    driver: local